# work flow name
name: Publish Docker Image
# when to trage this work flow
on:
    push:
        branches:
            - 'main'
# setup default working dir
defaults:
    run:
        shell: bash
        working-directory: ./

# the jobs to run this ci
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo '$secrets.a'
