name: GitHub Actions Demo
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v2
             - uses: actions/setup-node@v2
             with:
             node-version: '14'
             - run: npm install -g bats
             - run: bats -v
