# work flow name
name: Publish Docker Image
# when to trage this work flow
on: 
 push: 
  branches: 
   - 'main'

jobs: 
 test: 
  runs-on: ubuntu-latest
  steps:
   - name: aaa
     env: 
      super_secret: ${{secrets.a}}
     run: |
      echo $super_secret


