# work flow name
name: Publish Docker Image
# when to trage this work flow
on: 
 push: 
  branches: 
   - 'main'

jobs: 
 test: 
  runs-on: ubuntu-latest
  steps: 
   env:
    a: ${{secrets.a}}
   - run: echo '$a'


