# work flow name
name: Publish Docker Image
# when to trage this work flow
on:
 push:
  branches:  
   - 'main'
#  create:
#   tags: 
#    - v*

jobs: 
 test: 
  runs-on: ubuntu-latest
  env:
   TOKEN: ${{secrets.TOKEN}}
  steps:
   - run: echo "${{github.event.push.commits['message']}}"
   # - run: echo "\/\/npm.pkg.github.com\/:_authToken=${TOKEN}" > .npmrc
   # - run: echo "@szkj-web-he:registry=https:\/\/npm.pkg.github.com" > .npmrc
   # - run: npm publish
    #  - run: echo ${GITHUB_REF#refs/tags/}
  #  - run: ls
   



